"use client";

import { Link } from "@/i18n/routing";
import { ArrowLeft, Briefcase, CheckCircle2, ChevronDown, ChevronUp, Copy, Eye, RotateCcw, Send } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import { useMyCompany } from "@/core/hooks/company/use-my-company";
import { useCompanyJob } from "@/core/hooks/jobs/use-company-job";
import { useDuplicateCompanyJob } from "@/core/hooks/jobs/use-duplicate-company-job";
import { useReopenCompanyJob } from "@/core/hooks/jobs/use-reopen-company-job";
import { useRouter } from "@/i18n/routing";
import RecruitmentWorkspace from "./RecruitmentWorkspace";
import { usePublishCompanyJob } from "@/core/hooks/jobs/use-publish-company-job";
import { ApiError } from "@/core/types/api";
import { useCompanyApplications } from "@/core/hooks/applications/use-company-applications";
import { usePipelineStages } from "@/core/hooks/applications/use-pipeline-stages";
import StatCard from "@/components/dashboard/company/job-applied-applicants/StatCard";
import JobListingChart from "@/components/dashboard/company/job-applied-applicants/JobListingChart";
import TrafficChannelChart from "@/components/dashboard/company/job-applied-applicants/TrafficChannelChart";
import VisitorsByCountryStats from "@/components/dashboard/company/job-applied-applicants/VisitorsByCountryStats";

export default function CompanyJobATSPage({ jobId }: { jobId: string }) {
  const [tab, setTab] = useState<"applicants" | "details" | "analytics">("applicants");
  const company = useMyCompany();
  const job = useCompanyJob(company.data?.id, jobId);
  const router = useRouter();
  const reopen = useReopenCompanyJob(company.data?.id || "");
  const duplicate = useDuplicateCompanyJob(company.data?.id || "");
  const publish = usePublishCompanyJob(company.data?.id || "");
  if (company.isError || job.isError) return <div className="grid h-full place-items-center text-center"><div><p className="font-bold text-neutral-100">Unable to load this job ATS.</p><button onClick={() => { void company.refetch(); void job.refetch(); }} className="mt-4 bg-brand px-5 py-3 text-sm font-bold text-white">Try again</button></div></div>;
  if (company.isPending || job.isPending) return <div className="grid h-full place-items-center text-neutral-60">Loading ATS…</div>;
  if (!company.data || !job.data) return <div className="grid h-full place-items-center text-neutral-60">No company job found.</div>;
  const item = job.data;
  async function duplicateJob() { try { const copy = await duplicate.mutateAsync(jobId); toast.success("Offre dupliquée en brouillon."); router.push(`/company/job-listing/${copy.id}`); } catch { toast.error("Impossible de dupliquer cette offre."); } }
  async function reopenJob() { try { await reopen.mutateAsync(jobId); toast.success("Offre réouverte en brouillon."); } catch { toast.error("Impossible de réouvrir cette offre."); } }
  async function publishJob() { try { await publish.mutateAsync(jobId); toast.success("Offre publiée avec succès."); } catch (error) { toast.error(error instanceof ApiError ? error.message : "Impossible de publier cette offre."); } }
  return <main className="h-full overflow-y-auto bg-white px-4 pb-10 lg:px-8"><div className="w-full"><header className="flex flex-col gap-5 border-b border-brand-light-neutral py-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-5"><Link href="/company/job-listing" className="grid size-11 place-items-center text-neutral-100"><ArrowLeft size={31}/></Link><div><h1 className="text-[24px] font-bold leading-tight text-[#25324B]">{item.title}</h1><p className="mt-2 text-[16px] text-[#515B6F]">{item.category || "Non catégorisé"} · {item.employmentTypes.map(v=>v.replaceAll("_"," ")).join(", ")} · <b>{item.hiredCount}</b> / {item.hiringTarget} recruté(s)</p></div></div><div className="flex flex-wrap gap-2"><button onClick={() => void duplicateJob()} disabled={duplicate.isPending} className="inline-flex h-[50px] items-center gap-2 border border-brand-light-neutral px-4 font-bold text-brand"><Copy size={17}/>Dupliquer</button>{item.status === "DRAFT"&&<button onClick={()=>void publishJob()} className="inline-flex h-[50px] items-center gap-2 bg-brand px-4 font-bold text-white"><Send size={17}/>Publier</button>}{item.status === "CLOSED"&&<button onClick={()=>void reopenJob()} className="inline-flex h-[50px] items-center gap-2 bg-brand px-4 font-bold text-white"><RotateCcw size={17}/>Réouvrir</button>}<button className="inline-flex h-[50px] items-center gap-3 border border-brand-light-neutral px-5 font-bold text-brand"><ChevronDown size={19}/>Plus d’actions</button></div></header><nav className="flex gap-9 overflow-x-auto border-b border-brand-light-neutral">{([["applicants","Candidats"],["details","Détails du poste"],["analytics","Analyses"]] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`border-b-[3px] px-1 py-5 text-[15px] font-bold ${tab===key?"border-brand text-[#25324B]":"border-transparent text-[#7C8493]"}`}>{label}</button>)}</nav><div className="pt-6">{tab === "applicants" && <RecruitmentWorkspace jobId={jobId} companyId={company.data.id}/>} {tab === "details" && <JobDetailsPanel item={item}/>} {tab === "analytics" && <JobAnalyticsPanel companyId={company.data.id} jobId={jobId} applicants={item.applicantsCount}/>}</div></div></main>;
}

function JobDetailsPanel({ item }: { item: import("@/core/types/job").CompanyJob }) {
  const list = (value?: string | null) => value?.split(/\n|•/).map(v=>v.trim()).filter(Boolean) || [];
  return <section className="border border-brand-light-neutral bg-white p-6 lg:p-8"><div className="grid gap-10 lg:grid-cols-[minmax(0,2fr)_320px]"><div className="space-y-8"><TextBlock title="Description" value={item.description}/><ListBlock title="Responsabilités" values={list(item.responsibilities)}/><ListBlock title="Profil recherché" values={list(item.requirements)}/><ListBlock title="Atouts supplémentaires" values={list(item.niceToHave)}/></div><aside className="space-y-7"><div><h3 className="text-xl font-bold">À propos du poste</h3><div className="mt-4 bg-[#fafaff] p-4"><b>{item.applicantsCount} candidature(s)</b> sur {item.hiringTarget} poste(s)</div></div><Fact label="Type" value={item.employmentTypes.map(v=>v.replaceAll("_"," ")).join(", ")}/><Fact label="Lieu" value={item.location || "Non précisé"}/><Fact label="Salaire" value={item.minSalary || item.maxSalary ? `${item.minSalary ?? "—"} – ${item.maxSalary ?? "—"}` : "Non précisé"}/><div><h3 className="font-bold">Catégorie</h3><span className="mt-3 inline-block bg-accent-light-brand px-3 py-2 text-sm text-brand">{item.category || "Non précisée"}</span></div><div><h3 className="font-bold">Compétences requises</h3><div className="mt-3 flex flex-wrap gap-2">{item.skills.length ? item.skills.map(skill=><span key={skill} className="bg-[#fafaff] px-3 py-2 text-sm text-brand">{skill}</span>) : <span className="text-sm text-neutral-60">Aucune compétence renseignée</span>}</div></div></aside></div></section>;
}
function TextBlock({title,value}:{title:string;value?:string|null}) { return <div><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-neutral-80">{value || "Non renseigné"}</p></div> }
function ListBlock({title,values}:{title:string;values:string[]}) { return <div><h2 className="text-xl font-bold">{title}</h2>{values.length?<ul className="mt-3 space-y-3">{values.map((v,i)=><li key={i} className="flex gap-2 text-sm leading-6 text-neutral-80"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-[#56CDAD]"/>{v}</li>)}</ul>:<p className="mt-3 text-sm text-neutral-60">Non renseigné</p>}</div> }
function Fact({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4 border-b border-brand-light-neutral pb-4 text-sm"><span className="text-neutral-60">{label}</span><b className="text-right">{value}</b></div> }
function JobAnalyticsPanel({companyId,jobId,applicants}:{companyId:string;jobId:string;applicants:number}) { const applications=useCompanyApplications(companyId,{limit:100}),stages=usePipelineStages(companyId),rows=(applications.data?.data||[]).filter(row=>row.jobId===jobId),colors=["#FFB836","#26A4FF","#7B61FF","#56CDAD","#F65160"],traffic=(stages.data||[]).slice(0,5).map((stage,index)=>({name:stage.name,value:applicants?Math.round(rows.filter(row=>row.stageId===stage.id).length/applicants*100):0,color:colors[index]})); const emptyViews=["J-6","J-5","J-4","J-3","J-2","Hier","Aujourd’hui"].map(date=>({date,views:0})); return <section className="flex w-full items-stretch gap-5 max-lg:flex-col"><div className="flex w-2/3 flex-col gap-5 max-lg:w-full"><div className="flex gap-5 max-sm:flex-col"><StatCard title="Total Views" value={0} percentage="0%" trend="up" icon={<Eye size={18}/>} iconBgColor="bg-[#26A4FF]" trendColorClass="text-accent-green" trendIcon={<ChevronUp size={16}/>}/><StatCard title="Total Applied" value={applicants} percentage="0%" trend="down" icon={<Briefcase size={18}/>} iconBgColor="bg-brand" trendColorClass="text-accent-red" trendIcon={<ChevronDown size={16}/>}/></div><JobListingChart data={emptyViews}/></div><div className="flex w-1/3 flex-col gap-5 max-lg:w-full"><TrafficChannelChart data={traffic.length?traffic:[{name:"Aucune donnée",value:100,color:"#D6DDEB"}]}/><VisitorsByCountryStats data={[]}/></div></section> }
