"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { CalendarDays, CircleSlash2, Info, Mail, MapPin, Search, X } from "lucide-react";
import toast from "react-hot-toast";
import { useJobApplications } from "@/core/hooks/applications/use-job-applications";
import { usePipelineStages } from "@/core/hooks/applications/use-pipeline-stages";
import { useUpdateApplicationStage } from "@/core/hooks/applications/use-update-application-stage";
import { useCreateInterview } from "@/core/hooks/interviews/use-create-interview";
import { mediaUrl } from "@/core/lib/media-url";
import type { CompanyApplication, PipelineStage } from "@/core/types/application";

export default function RecruitmentWorkspace({ jobId, companyId }: { jobId: string; companyId: string }) {
  const [tab, setTab] = useState<"applications" | "pipeline" | "rejected">("applications");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [details, setDetails] = useState<CompanyApplication | null>(null);
  const [schedule, setSchedule] = useState<CompanyApplication | null>(null);
  const applications = useJobApplications(jobId, { search: query, limit: 100 });
  const stages = usePipelineStages(companyId);
  const updateStage = useUpdateApplicationStage(jobId);
  const orderedStages = useMemo(() => [...(stages.data ?? [])].sort((a, b) => a.order - b.order), [stages.data]);
  const rejectedStage = orderedStages.find((stage) => /reject/i.test(stage.name));
  const rows = applications.data?.data ?? [];
  const visibleRows = tab === "rejected" ? rows.filter((row) => row.stageId === rejectedStage?.id) : rows.filter((row) => row.stageId !== rejectedStage?.id);

  async function move(applicationIds: string[], stage: PipelineStage) {
    try {
      await Promise.all(applicationIds.map((applicationId) => updateStage.mutateAsync({ applicationId, stageId: stage.id })));
      setSelected([]);
      toast.success(`${applicationIds.length} candidature(s) déplacée(s) vers ${stage.name}`);
    } catch { toast.error("Impossible de modifier l’étape de recrutement."); }
  }

  if (applications.isPending || stages.isPending) return <div className="grid min-h-96 place-items-center border border-brand-light-neutral text-neutral-60">Chargement des candidatures…</div>;
  if (applications.isError || stages.isError) return <div className="grid min-h-96 place-items-center border border-brand-light-neutral text-center"><div><p className="font-bold">Impossible de charger l’ATS.</p><button onClick={() => { void applications.refetch(); void stages.refetch(); }} className="mt-3 bg-brand px-4 py-2 text-sm font-bold text-white">Réessayer</button></div></div>;

  return <section className="border border-brand-light-neutral bg-white"><header className="flex flex-col gap-4 border-b border-brand-light-neutral px-4 py-4 lg:flex-row lg:items-center lg:justify-between lg:px-6"><nav className="flex gap-6 overflow-x-auto">{([ ["applications", "Applications"], ["pipeline", "Processus de recrutement"], ["rejected", "Rejetées"] ] as const).map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`relative whitespace-nowrap py-2 text-sm font-semibold ${tab === key ? "text-brand" : "text-neutral-60"}`}>{label}{tab === key && <span className="absolute inset-x-0 -bottom-4 h-0.5 bg-brand"/>}</button>)}</nav><label className="flex h-10 items-center gap-2 border border-brand-light-neutral px-3 text-neutral-60"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un candidat" className="w-64 max-w-full bg-transparent text-sm outline-none"/></label></header>
    {tab === "pipeline" ? <Pipeline rows={rows.filter((row) => row.stageId !== rejectedStage?.id)} stages={orderedStages.filter((stage) => stage.id !== rejectedStage?.id)} onMove={move} onDetails={setDetails} onSchedule={setSchedule}/> : <ApplicationTable rows={visibleRows} stages={orderedStages} selected={selected} setSelected={setSelected} onMove={move} onDetails={setDetails} onSchedule={setSchedule} rejectedStage={rejectedStage}/>}
    {details && <DetailsModal application={details} onClose={() => setDetails(null)}/>} {schedule && <ScheduleModal application={schedule} companyId={companyId} onClose={() => setSchedule(null)}/>} </section>;
}

function ApplicationTable({ rows, stages, selected, setSelected, onMove, onDetails, onSchedule, rejectedStage }: { rows: CompanyApplication[]; stages: PipelineStage[]; selected: string[]; setSelected: (ids: string[]) => void; onMove: (ids: string[], stage: PipelineStage) => Promise<void>; onDetails: (row: CompanyApplication) => void; onSchedule: (row: CompanyApplication) => void; rejectedStage?: PipelineStage }) {
  const [target, setTarget] = useState("");
  return <div className="p-4 lg:p-6">{selected.length > 0 && <div className="mb-4 flex flex-wrap items-center gap-3 bg-accent-light-brand p-3"><b className="mr-auto text-sm">{selected.length} sélectionnée(s)</b><select value={target} onChange={(event) => setTarget(event.target.value)} className="h-9 border border-brand-light-neutral bg-white px-3 text-sm"><option value="">Choisir une étape</option>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select><button disabled={!target} onClick={() => { const stage = stages.find((item) => item.id === target); if (stage) void onMove(selected, stage); }} className="h-9 bg-brand px-4 text-sm font-bold text-white disabled:opacity-50">Déplacer</button></div>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-y border-brand-light-neutral text-xs uppercase text-neutral-60"><tr><th className="w-12 px-3 py-4"><input type="checkbox" checked={rows.length > 0 && selected.length === rows.length} onChange={() => setSelected(selected.length === rows.length ? [] : rows.map((row) => row.id))}/></th><th>Candidat</th><th>Date</th><th>Localisation</th><th>Étape</th><th>Evaluation</th><th className="text-right">Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-[#edf0f6] hover:bg-[#fafaff]"><td className="px-3 py-3"><input type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected(selected.includes(row.id) ? selected.filter((id) => id !== row.id) : [...selected, row.id])}/></td><td><CandidateIdentity row={row}/></td><td className="text-neutral-60">{new Date(row.appliedAt).toLocaleDateString()}</td><td className="text-neutral-60">{row.candidate?.candidateProfile?.location || "Non renseignée"}</td><td><span className="bg-accent-light-brand px-2 py-1 text-xs font-semibold text-brand">{row.stage?.name || "Non assignée"}</span></td><td><Score score={row.score}/></td><td><div className="flex justify-end gap-1"><button onClick={() => onDetails(row)} title="Détails" className="grid size-9 place-items-center hover:bg-accent-light-brand"><Info size={16}/></button><button onClick={() => onSchedule(row)} title="Planifier" className="grid size-9 place-items-center text-brand hover:bg-accent-light-brand"><CalendarDays size={16}/></button>{rejectedStage && row.stageId !== rejectedStage.id && <button onClick={() => void onMove([row.id], rejectedStage)} title="Rejeter" className="grid size-9 place-items-center text-accent-red hover:bg-accent-light-red"><CircleSlash2 size={16}/></button>}</div></td></tr>)}{rows.length === 0 && <tr><td colSpan={7} className="py-16 text-center text-neutral-60">Aucune candidature dans cette section.</td></tr>}</tbody></table></div></div>;
}

function Pipeline({ rows, stages, onMove, onDetails, onSchedule }: { rows: CompanyApplication[]; stages: PipelineStage[]; onMove: (ids: string[], stage: PipelineStage) => Promise<void>; onDetails: (row: CompanyApplication) => void; onSchedule: (row: CompanyApplication) => void }) {
  const [over, setOver] = useState<string | null>(null);
  return <div className="overflow-x-auto p-4 lg:p-6"><div className="grid min-w-[1000px] gap-3" style={{ gridTemplateColumns: `repeat(${Math.max(stages.length, 1)}, minmax(210px, 1fr))` }}>{stages.map((stage) => { const items = rows.filter((row) => row.stageId === stage.id); return <section key={stage.id} onDragOver={(event) => { event.preventDefault(); setOver(stage.id); }} onDragLeave={() => setOver(null)} onDrop={(event) => { event.preventDefault(); const id = event.dataTransfer.getData("application/id"); setOver(null); if (id) void onMove([id], stage); }} className={`min-h-[460px] border-2 p-3 ${over === stage.id ? "border-brand bg-accent-light-brand" : "border-transparent bg-[#f8f8fb]"}`}><h3 className="mb-4 text-center text-sm font-bold text-brand">{stage.name} <span className="text-neutral-60">({items.length})</span></h3><div className="space-y-3">{items.map((row) => <article key={row.id} draggable onDragStart={(event) => event.dataTransfer.setData("application/id", row.id)} className="cursor-grab border border-[#e8eaf2] bg-white p-3 shadow-sm hover:border-brand"><CandidateIdentity row={row}/><div className="mt-3 flex justify-end gap-2"><button onClick={() => onDetails(row)} className="text-xs font-semibold text-brand">Détails</button><button onClick={() => onSchedule(row)} className="text-xs font-semibold text-brand">Planifier</button></div></article>)}</div></section>; })}</div></div>;
}

function CandidateIdentity({ row }: { row: CompanyApplication }) { const avatar = mediaUrl(row.candidate?.avatar); return <div className="flex items-center gap-3">{avatar ? <Image src={avatar} alt="" width={36} height={36} className="size-9 rounded-full object-cover"/> : <span className="grid size-9 place-items-center rounded-full bg-accent-light-brand font-bold text-brand">{row.fullName.slice(0, 1).toUpperCase()}</span>}<div className="min-w-0"><p className="truncate font-semibold text-neutral-100">{row.fullName}</p><p className="truncate text-xs text-neutral-60">{row.currentJobTitle || row.candidate?.candidateProfile?.headline || "Candidat"}</p></div></div>; }
function Score({ score }: { score: number | null }) { return <span className="inline-flex min-w-14 justify-center bg-accent-light-brand px-2 py-1 text-xs font-bold text-brand">{score == null ? "—" : `${Number(score).toFixed(1)}/5`}</span>; }

function DetailsModal({ application, onClose }: { application: CompanyApplication; onClose: () => void }) { return <Modal onClose={onClose}><h2 className="text-xl font-bold">Détails du candidat</h2><div className="mt-5"><CandidateIdentity row={application}/></div><div className="mt-6 space-y-3 border-y border-brand-light-neutral py-5 text-sm"><p className="flex gap-2"><Mail size={16} className="text-brand"/>{application.email}</p><p className="flex gap-2"><MapPin size={16} className="text-brand"/>{application.candidate?.candidateProfile?.location || "Localisation non renseignée"}</p>{application.phone && <p>{application.phone}</p>}{application.linkedinUrl && <a className="block text-brand underline" href={application.linkedinUrl} target="_blank" rel="noreferrer">LinkedIn</a>}{application.portfolioUrl && <a className="block text-brand underline" href={application.portfolioUrl} target="_blank" rel="noreferrer">Portfolio</a>}</div>{application.coverLetter && <div className="mt-5"><h3 className="font-bold">Lettre de motivation</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-neutral-60">{application.coverLetter}</p></div>}</Modal>; }

function ScheduleModal({ application, companyId, onClose }: { application: CompanyApplication; companyId: string; onClose: () => void }) {
  const create = useCreateInterview(companyId); const [scheduledAt, setScheduledAt] = useState(""); const [duration, setDuration] = useState(60); const [title, setTitle] = useState("Entretien");
  async function submit() { if (!scheduledAt) return; const start = new Date(scheduledAt); try { await create.mutateAsync({ applicationId: application.id, companyId, title, scheduledAt: start.toISOString(), endTime: new Date(start.getTime() + duration * 60_000).toISOString(), location: "En ligne" }); toast.success("Entretien planifié."); onClose(); } catch { toast.error("Impossible de planifier cet entretien."); } }
  return <Modal onClose={onClose}><h2 className="text-xl font-bold">Planifier un entretien</h2><div className="mt-4"><CandidateIdentity row={application}/></div><div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Objet<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 h-11 w-full border border-brand-light-neutral px-3 font-normal"/></label><label className="block text-sm font-semibold">Date et heure<input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} className="mt-2 h-11 w-full border border-brand-light-neutral px-3 font-normal"/></label><label className="block text-sm font-semibold">Durée<select value={duration} onChange={(event) => setDuration(Number(event.target.value))} className="mt-2 h-11 w-full border border-brand-light-neutral bg-white px-3 font-normal"><option value={30}>30 minutes</option><option value={60}>1 heure</option><option value={90}>1 h 30</option></select></label><button disabled={!scheduledAt || create.isPending} onClick={() => void submit()} className="h-11 w-full bg-brand font-bold text-white disabled:opacity-50">{create.isPending ? "Planification…" : "Planifier"}</button></div></Modal>;
}
function Modal({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-neutral-100/55 p-4" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="relative max-h-[90vh] w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><button onClick={onClose} className="absolute right-3 top-3 grid size-9 place-items-center"><X size={18}/></button>{children}</div></div>; }
