"use client";

import { ArrowLeft, BriefcaseBusiness, Mail, Phone, Star } from "lucide-react";
import { Link } from "@/i18n/routing";
import { useApplication } from "@/core/hooks/applications/use-application";

export default function CompanyApplicantDetails({ applicationId }: { applicationId: string }) {
  const application = useApplication(applicationId);
  if (application.isPending) return <p className="py-20 text-center text-neutral-60">Chargement de la candidature…</p>;
  if (application.isError || !application.data) return <div className="py-20 text-center"><p className="font-bold">Candidature introuvable ou inaccessible.</p><Link href="/company/applicants" className="mt-4 inline-flex bg-brand px-5 py-2 text-white">Retour aux candidats</Link></div>;
  const row = application.data; const score = row.score == null ? null : row.score <= 1 ? Math.round(row.score * 100) : Math.round(row.score);
  return <main className="h-full overflow-y-auto bg-white px-4 py-6 lg:px-8"><Link href="/company/applicants" className="inline-flex items-center gap-2 text-sm font-semibold text-brand"><ArrowLeft size={17}/>Candidats</Link><div className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="border border-brand-light-neutral p-6"><span className="grid size-20 place-items-center rounded-full bg-accent-light-brand text-2xl font-bold text-brand">{row.fullName.slice(0,2).toUpperCase()}</span><h1 className="mt-4 text-2xl font-bold">{row.fullName}</h1><p className="text-sm text-neutral-60">{row.currentJobTitle || "Candidat"}</p><div className="mt-6 space-y-3 text-sm"><p className="flex gap-2"><Mail size={16} className="text-brand"/>{row.email}</p><p className="flex gap-2"><Phone size={16} className="text-brand"/>{row.phone || "Non renseigné"}</p><p className="flex gap-2"><Star size={16} className="text-brand"/>{score == null ? "Matching non calculé" : `${score}% de matching`}</p></div></aside><section className="border border-brand-light-neutral p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-neutral-60">Candidature</p><h2 className="mt-1 text-xl font-bold">{row.job?.title}</h2></div><span className="bg-accent-light-brand px-3 py-2 text-sm font-bold text-brand">{row.stage?.name || "Non assignée"}</span></div><div className="mt-6 flex flex-wrap gap-4 border-y border-brand-light-neutral py-4 text-sm text-neutral-60"><span className="flex gap-2"><BriefcaseBusiness size={16}/>{row.job?.location || "Remote"}</span><span>Reçue le {new Date(row.appliedAt).toLocaleDateString()}</span></div>{row.coverLetter && <div className="mt-6"><h3 className="font-bold">Lettre de motivation</h3><p className="mt-3 whitespace-pre-wrap leading-7 text-neutral-80">{row.coverLetter}</p></div>}<div className="mt-7 flex flex-wrap gap-3">{row.linkedinUrl && <a href={row.linkedinUrl} target="_blank" rel="noreferrer" className="border border-brand px-4 py-2 text-sm font-semibold text-brand">LinkedIn</a>}{row.portfolioUrl && <a href={row.portfolioUrl} target="_blank" rel="noreferrer" className="border border-brand px-4 py-2 text-sm font-semibold text-brand">Portfolio</a>}<Link href={`/company/job-listing/${row.jobId}`} className="bg-brand px-4 py-2 text-sm font-semibold text-white">Ouvrir l’ATS</Link></div></section></div></main>;
}
