"use client";
import { useState } from "react";
import { ArrowLeft, CalendarDays, ChevronDown, Mail, Phone, Star } from "lucide-react";
import toast from "react-hot-toast";
import { Link } from "@/i18n/routing";
import { useApplication } from "@/core/hooks/applications/use-application";
import { useApplicationHistory } from "@/core/hooks/applications/use-application-history";
import { useUpdateApplicationScore } from "@/core/hooks/applications/use-update-application-score";
import { useApplicationInterviews } from "@/core/hooks/interviews/use-application-interviews";
import { useAddInterviewFeedback } from "@/core/hooks/interviews/use-add-interview-feedback";
import { usePlatformReferences } from "@/core/hooks/references/use-platform-references";
import { useProfessions } from "@/core/hooks/references/use-professions";

type Tab="profile"|"resume"|"progress"|"interviews";
export default function CompanyApplicantDetails({applicationId}:{applicationId:string}) {
 const [tab,setTab]=useState<Tab>("profile"),[rating,setRating]=useState(0),[feedbacks,setFeedbacks]=useState<Record<string,string>>({});
 const application=useApplication(applicationId),history=useApplicationHistory(applicationId),interviews=useApplicationInterviews(applicationId),updateScore=useUpdateApplicationScore(applicationId),addFeedback=useAddInterviewFeedback(applicationId);
 const languages=usePlatformReferences("language"),professions=useProfessions();
 if(application.isPending)return <Empty text="Chargement de la candidature…"/>;
 if(application.isError||!application.data)return <div className="py-20 text-center"><p className="font-bold">Candidature introuvable ou inaccessible.</p><Link href="/company/applicants" className="mt-4 inline-flex bg-brand px-5 py-2 text-white">Retour</Link></div>;
 const row=application.data,currentRating=rating||row.score||0,profile=row.candidate?.candidateProfile||undefined;
 async function saveRating(value:number){setRating(value);try{await updateScore.mutateAsync(value);toast.success("Évaluation enregistrée.")}catch{toast.error("Impossible d’enregistrer l’évaluation.")}}
 async function saveFeedback(id:string){const feedback=feedbacks[id]?.trim();if(!feedback)return;try{await addFeedback.mutateAsync({interviewId:id,feedback});setFeedbacks(v=>({...v,[id]:""}));toast.success("Feedback enregistré.")}catch{toast.error("Impossible d’enregistrer le feedback.")}}
 return <main className="h-full overflow-y-auto bg-[#f8f8fb] px-4 py-6 lg:px-8"><div className="mb-6 flex items-center gap-4"><Link href="/company/applicants" className="grid size-10 place-items-center"><ArrowLeft size={30}/></Link><h1 className="text-[26px] font-bold">Détails du candidat</h1><button className="ml-auto inline-flex h-[50px] items-center gap-3 border border-brand-light-neutral bg-white px-5 font-bold text-brand"><ChevronDown size={18}/>Plus d’actions</button></div><div className="grid gap-8 xl:grid-cols-[350px_minmax(0,1fr)]">
  <aside className="h-fit border border-brand-light-neutral bg-white p-6"><div className="flex items-center gap-4"><span className="grid size-20 shrink-0 place-items-center rounded-full bg-accent-light-brand text-2xl font-bold text-brand">{row.fullName.slice(0,2).toUpperCase()}</span><div><h2 className="text-xl font-bold">{row.fullName}</h2><p className="text-neutral-60">{row.currentJobTitle||"Candidat"}</p><p className="mt-2 flex items-center gap-1 text-sm"><Star size={17} className="fill-[#FFB836] text-[#FFB836]"/>{Number(currentRating).toFixed(1)}</p></div></div><div className="mt-6 bg-[#fafaff] p-4"><p className="text-xs text-neutral-60">Poste demandé</p><p className="mt-2 font-bold">{row.job?.title}</p><p className="mt-1 text-sm text-neutral-60">{row.job?.location||"Remote"}</p></div><div className="mt-5"><p className="text-sm text-neutral-60">Étape actuelle</p><p className="mt-2 font-bold text-brand">{row.stage?.name||"Non assignée"}</p><div className="mt-3 h-2 bg-[#e5e8f1]"><div className="h-full w-2/3 bg-[#26A4FF]"/></div></div><div className="mt-6 border-t border-brand-light-neutral pt-5"><p className="font-bold">Évaluation recruteur</p><div className="mt-3 flex gap-1">{[1,2,3,4,5].map(v=><button key={v} onClick={()=>void saveRating(v)}><Star size={23} className={v<=currentRating?"fill-[#FFB836] text-[#FFB836]":"text-neutral-40"}/></button>)}</div></div><div className="mt-6 space-y-4 border-t border-brand-light-neutral pt-5 text-sm"><h3 className="text-lg font-bold">Contact</h3><p className="flex gap-3"><Mail size={18}/>{row.email}</p><p className="flex gap-3"><Phone size={18}/>{row.phone||"Non renseigné"}</p>{row.linkedinUrl&&<a href={row.linkedinUrl} target="_blank" rel="noreferrer" className="block text-brand">LinkedIn</a>}{row.portfolioUrl&&<a href={row.portfolioUrl} target="_blank" rel="noreferrer" className="block text-brand">Portfolio</a>}</div></aside>
  <section className="min-w-0 border border-brand-light-neutral bg-white"><nav className="flex overflow-x-auto border-b border-brand-light-neutral px-4">{([["profile","Profil"],["resume","CV"],["progress","Progression"],["interviews","Entretiens"]] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap border-b-2 px-5 py-5 text-sm font-bold ${tab===key?"border-brand text-neutral-100":"border-transparent text-neutral-60"}`}>{label}</button>)}</nav><div className="p-5 lg:p-7">
   {tab==="profile"&&<div className="space-y-8"><div><h3 className="text-lg font-bold">Informations personnelles</h3><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Nom complet" value={row.fullName}/><Info label="Email" value={row.email}/><Info label="Téléphone" value={row.phone||"Non renseigné"}/><Info label="Profession" value={row.candidate?.profession?.name||"Non renseignée"}/><Info label="Poste actuel" value={row.currentJobTitle||profile?.headline||"Non renseigné"}/><Info label="Localisation" value={[profile?.cityName,profile?.countryName].filter(Boolean).join(", ")||"Non renseignée"}/><Info label="Expérience" value={profile?.yearsExperience!=null?`${profile.yearsExperience} an(s)`:"Non renseignée"}/></dl>{profile?.bio&&<p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-neutral-80">{profile.bio}</p>}</div><ProfilePreferences profile={profile} languages={languages.data||[]} professions={professions.data||[]}/><ProfileHistory profile={profile}/><div className="border-t border-brand-light-neutral pt-7"><h3 className="text-lg font-bold">Lettre de motivation</h3><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-neutral-80">{row.coverLetter||"Aucune lettre de motivation."}</p></div></div>}
   {tab==="resume"&&(row.resume?<div><div className="mb-4 flex items-center justify-between gap-3"><h3 className="text-lg font-bold">{row.resume.title||"Curriculum vitae"}</h3><a href={`/api/proxy/applications/${applicationId}/resume`} target="_blank" rel="noreferrer" className="bg-brand px-4 py-2 text-sm font-bold text-white">Ouvrir le CV</a></div><iframe title="CV du candidat" src={`/api/proxy/applications/${applicationId}/resume`} className="h-[720px] w-full border"/></div>:<Empty text="Aucun CV attaché à cette candidature."/>)}
   {tab==="progress"&&<div><h3 className="text-lg font-bold">Progression du recrutement</h3><div className="mt-5 bg-accent-light-brand p-4 font-bold text-brand">Étape actuelle : {row.stage?.name||"Non assignée"}</div><ol className="mt-7 space-y-4">{history.data?.map(item=><li key={item.id} className="border-l-2 border-brand pl-4"><p className="font-semibold">{item.oldStageName} → {item.newStageName}</p><p className="mt-1 text-xs text-neutral-60">{new Date(item.createdAt).toLocaleString()}</p>{item.note&&<p className="mt-2 text-sm">{item.note}</p>}</li>)}{!history.data?.length&&<Empty text="Aucun changement enregistré."/>}</ol></div>}
   {tab==="interviews"&&<div><h3 className="flex items-center gap-2 text-lg font-bold"><CalendarDays size={20} className="text-brand"/>Entretiens planifiés</h3><div className="mt-5 space-y-4">{interviews.data?.map(i=><article key={i.id} className="border p-5"><div className="flex justify-between gap-3"><div><h4 className="font-bold">{i.title}</h4><p className="mt-1 text-sm text-neutral-60">{new Date(i.scheduledAt).toLocaleString()} · {i.location||"En ligne"}</p></div><b className="text-xs text-brand">{i.status}</b></div>{i.feedback?<p className="mt-4 bg-[#fafaff] p-3 text-sm">{i.feedback}</p>:<div className="mt-4 flex gap-2"><textarea value={feedbacks[i.id]||""} onChange={e=>setFeedbacks(v=>({...v,[i.id]:e.target.value}))} className="min-h-20 flex-1 border p-3" placeholder="Ajouter un feedback"/><button onClick={()=>void saveFeedback(i.id)} className="self-end bg-brand px-4 py-2 text-sm font-bold text-white">Enregistrer</button></div>}</article>)}{!interviews.data?.length&&<Empty text="Aucun entretien planifié."/>}</div></div>}
  </div></section></div></main>;
}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-sm text-neutral-60">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
function Empty({text}:{text:string}){return <p className="py-10 text-center text-sm text-neutral-60">{text}</p>}
function ProfilePreferences({profile,languages,professions}:{profile:NonNullable<NonNullable<import("@/core/types/application").CompanyApplication["candidate"]>["candidateProfile"]>|undefined;languages:Array<{code:string;name:string}>;professions:Array<{id:string;name:string}>}){if(!profile)return <Empty text="Profil professionnel non renseigné."/>;const items=[...(profile.preferredProfessionIds||[]).map(id=>professions.find(item=>item.id===id)?.name||id),...(profile.preferredCountries||[]),...(profile.preferredEmploymentTypes||[]).map(item=>item.replaceAll("_"," ")),profile.acceptsRemote?"Télétravail accepté":null].filter(Boolean) as string[];return <div className="border-t pt-7"><h3 className="text-lg font-bold">Préférences professionnelles</h3><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Disponibilité" value={profile.availability||"Non renseignée"}/><Info label="Mode de travail" value={profile.workType||"Non renseigné"}/><Info label="Salaire attendu" value={profile.expectedSalaryMin||profile.expectedSalaryMax?`${profile.expectedSalaryMin||"—"} – ${profile.expectedSalaryMax||"—"} ${profile.salaryCurrency||"USD"}`:"Non renseigné"}/></dl><div className="mt-5 flex flex-wrap gap-2">{items.map(item=><span key={item} className="bg-indigo-50 px-3 py-2 text-sm text-brand">{item}</span>)}</div><h4 className="mt-6 font-bold">Langues</h4><div className="mt-3 flex flex-wrap gap-2">{(profile.languageProficiencies||[]).map(item=><span key={item.code} className="bg-[#f5f5f8] px-3 py-2 text-sm">{languages.find(language=>language.code.toLowerCase()===item.code.toLowerCase())?.name||item.code.toUpperCase()} · {item.level}</span>)}</div></div>}
function ProfileHistory({profile}:{profile:NonNullable<NonNullable<import("@/core/types/application").CompanyApplication["candidate"]>["candidateProfile"]>|undefined}){if(!profile)return null;return <div className="border-t pt-7"><h3 className="text-lg font-bold">Parcours complet</h3><div className="mt-4 space-y-4">{profile.candidateSkills?.length?<div><b>Compétences</b><p className="mt-2 text-sm">{profile.candidateSkills.map(item=>item.skill?.name).filter(Boolean).join(", ")}</p></div>:null}{profile.candidateExperiences?.map(item=><article key={item.id}><b>{item.jobTitle||"Expérience"}</b><p className="text-sm text-brand">{item.companyName}</p>{item.description&&<p className="mt-1 text-sm text-neutral-60">{item.description}</p>}</article>)}{profile.candidate_educations?.map(item=><article key={item.id}><b>{item.degree||"Formation"}</b><p className="text-sm text-neutral-60">{item.institution} {item.fieldOfStudy&&`· ${item.fieldOfStudy}`}</p></article>)}{profile.candidateCertifications?.map(item=><article key={item.id}><b>{item.name||"Certification"}</b><p className="text-sm text-neutral-60">{item.issuingOrganization}</p></article>)}{profile.candidatePortfolios?.map(item=><article key={item.id}><b>{item.title||"Projet"}</b>{item.projectUrl&&<a href={item.projectUrl} target="_blank" rel="noreferrer" className="ml-3 text-sm text-brand">Voir le projet</a>}</article>)}</div></div>}
