import type { Metadata } from "next";
import { Ubuntu, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { AppProvider } from "@/context/AppContext";

const ubuntuSans = Ubuntu({
    variable: "--font-ubuntu-sans",
    subsets: ["latin"],
    weight: ["300", "400", "500", "700"],
});

const ubuntuMono = Ubuntu_Mono({
    variable: "--font-ubuntu-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Hr",
    description: "Generated by Infinity Innovations",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();
    const messages = await getMessages();

    return (
        <html
            lang={locale}
            className={`${ubuntuSans.variable} ${ubuntuMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col font-sans">
        <NextIntlClientProvider messages={messages}>
            <AppProvider>{children}</AppProvider>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
