import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { AppProvider } from "@/context/AppContext";
import Navbar from "../../components/shared/Navbar";
import Footer from "../../components/shared/Footer";
import { Manrope, Archivo_Black } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo-black",
});

export const metadata: Metadata = {
  title: "Hr",
  description: "Generated by Infinity Innovations",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`${manrope.className} ${archivoBlack.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col font-sans overflow-x-hidden">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          <AppProvider>{children}</AppProvider>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
