"use client";

import { useCompany } from "@/core/hooks/company/use-company";
import { Building2, ExternalLink, MapPin } from "lucide-react";
import Image from "next/image";

export function PublicCompanyProfile({ id }: { id: string }) {
  const company = useCompany(id);
  if (company.isPending) return <div className="grid min-h-[60vh] place-items-center">Loading company…</div>;
  if (company.isError || !company.data) return <div className="grid min-h-[60vh] place-items-center text-accent-red">Company not found.</div>;
  const item = company.data;
  return <main className="pb-16"><div className="relative h-56 bg-gradient-to-r from-slate-900 to-cyan-800">{item.coverImage && <Image src={item.coverImage} alt="" fill className="object-cover"/>}</div><div className="mx-auto max-w-7xl px-4 md:px-12"><div className="-mt-12 flex items-end gap-4">{item.logo ? <Image src={item.logo} alt={item.name} width={112} height={112} className="z-10 size-28 border-4 border-white bg-white object-contain"/> : <span className="z-10 grid size-28 place-items-center border-4 border-white bg-white"><Building2 size={42}/></span>}<div className="pb-2"><h1 className="text-3xl font-bold">{item.name}</h1><p className="flex items-center gap-1 text-sm text-neutral-60"><MapPin size={14}/>{item.location || "Remote"}</p></div></div><div className="mt-10 grid gap-10 lg:grid-cols-[2fr_1fr]"><article><h2 className="text-2xl font-bold">About</h2><p className="mt-4 whitespace-pre-line leading-7 text-neutral-80">{item.description || "No description available."}</p>{item.gallery.length > 0 && <div className="mt-8 grid grid-cols-2 gap-3">{item.gallery.map((src) => <div key={src} className="relative aspect-video"><Image src={src} alt="Company" fill className="object-cover"/></div>)}</div>}<h2 className="mt-10 text-2xl font-bold">Benefits</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{item.perks.map((perk) => <div key={perk.title} className="border p-4"><b className="text-brand">{perk.title}</b><p className="mt-2 text-sm text-neutral-60">{perk.description}</p></div>)}</div></article><aside><h2 className="text-xl font-bold">Company details</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-neutral-60">Industry</dt><dd className="font-bold">{item.industry || "—"}</dd></div><div><dt className="text-neutral-60">Company size</dt><dd className="font-bold">{item.companySize || "—"}</dd></div><div><dt className="text-neutral-60">Locations</dt><dd className="font-bold">{item.locations.join(", ") || item.location || "—"}</dd></div></dl>{item.website && <a href={item.website} target="_blank" rel="noreferrer" className="mt-6 flex items-center gap-2 font-bold text-brand">Visit website <ExternalLink size={15}/></a>}<h2 className="mt-8 text-xl font-bold">Tech stack</h2><div className="mt-3 flex flex-wrap gap-2">{item.techStack.map((tech) => <span key={tech} className="bg-accent-light-brand px-3 py-2 text-xs font-bold text-brand">{tech}</span>)}</div></aside></div></div></main>;
}
